name: Build and Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Action / Checkout
        uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Action / Setup Node v16
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: Action / Install Dependencies
        run: |
          yarn install

      - name: Action / Build
        run: |
          yarn run prod

      - name: Action / Release
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: I have released a new version!
          file_pattern: dist/*.js
          branch: master
          push_options: --force
